### ISSUE TITLE
Fog vsphere cannot vm_clone on VVOL

### ISSUE THREAD

**Issue by chiccat** [fog/fog-vsphere#155]
Hi guys,
Here's an issues I faced in foreman.
I was checking the source of foreman, but after realized it's an issue with this gem.

Code:
opts = {"datacenter"=>"DC1",
  "template_path"=>"Templates/centos75",
  "dest_folder"=>"/Datacenters/DC1/vm",
  "power_on"=>false,
  "start"=>"1",
  "name"=>"testvm.example.com",
  "numCPUs"=>"1",
  "numCoresPerSocket"=>"1",
  "memoryMB"=>"768",
  "datastore"=>"DC1-CL1-VVOL-00",
  "storage_pod"=>nil,
  "resource_pool"=>["DC1-CL1-1", "Resources"],
  "transform"=>"flat"
}

Error:
/Library/Ruby/Gems/2.3.0/gems/rbvmomi-1.11.6/lib/rbvmomi/vim/Task.rb:14:in `wait_for_completion': FileFault: Error caused by file /vmfs/volumes/vvol:431b35dbe8d13fb0-94d4d9979b98d473/rfc4122.a898615e-124d-4588-935b-f456a8a7bdf5/centos75.vmdk (RbVmomi::Fault)
	from /Library/Ruby/Gems/2.3.0/gems/fog-vsphere-2.3.0/lib/fog/vsphere/requests/compute/vm_clone.rb:693:in `vm_clone'
	from /tmp/333:51:in `<main>'
[Finished in 23.39s]

Thank you

**Comment by chris1984** [comment]
@chiccat Thanks for the issue, we will take a look.
