### ISSUE TITLE
Failed to destroy VM interface with v2.4.0 

### ISSUE THREAD

**Issue by kensoncheung** [fog/fog-vsphere#166]
Hi there,

  I have encountered several issues in destroying VM interface.
  1. datacenter' is a required parameter in options
  - There is a pull request for patching this: https://github.com/fog/fog-vsphere/pull/165/files
  - I have also tried to fill in datacenter or put the interface object to options instead.
  - After doing so, I encountered another issue. (see #2)
  
  2. `public_send': undefined method `networkFolder' for nil:NilClass (NoMethodError)
  - From  the source code, it seems like dc object is nil.

thanks,
Kenson

```
#! /usr/bin/env ruby

require 'fog/vsphere'

server   = '192.168.10.123'
port     = 443
username = 'administrator@vsphere.local'
password = 'password'
pubkey   = '68a9c69a0473700d17c286a7ab13123b1e4a163d321e121ac80c29c94bc25123'

conn = Fog::Compute::Vsphere.new(
  vsphere_server:               server,
  vsphere_port:                 port,
  vsphere_username:             username,
  vsphere_password:             password,
  vsphere_ssl:                  true,
  vsphere_expected_pubkey_hash: pubkey
)

vm_id = '5016d499-4604-ccda-93cb-208566b29c9a'
vm = conn.servers.get(vm_id)

# # @note Failed at .get()
# # Traceback (most recent call last):
# # 	3: from test.rb:21:in `<main>'
# # 	2: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/models/compute/interfaces.rb:32:in `get'
# # 	1: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/list_vm_interfaces.rb:36:in `get_vm_interface'
# # /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/list_vm_interfaces.rb:52:in `get_raw_interface': 'datacenter' is a required parameter in options: {:key=>4000, :mac=>4000, :name=>4000} (ArgumentError)
# interface = vm.interfaces.get(4000)


# # @note Failed at .destroy()
# # Traceback (most recent call last):
# # 	5: from test.rb:31:in `<main>'
# # 	4: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/models/compute/interface.rb:47:in `destroy'
# # 	3: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/modify_vm_interface.rb:15:in `destroy_vm_interface'
# # 	2: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/modify_vm_interface.rb:51:in `get_interface_from_options'
# # 	1: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/list_vm_interfaces.rb:36:in `get_vm_interface'
# # /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/list_vm_interfaces.rb:52:in `get_raw_interface': 'datacenter' is a required parameter in options: {:key=>4000, :type=>RbVmomi::VIM::VirtualVmxnet3, :server_id=>"5016d499-4604-ccda-93cb-208566b29c9a"} (ArgumentError)
# vm.interfaces.first.destroy


# # @note Failed at destroy_vm_interface() when bypassede datacenter
# # Traceback (most recent call last):
# # 	7: from test.rb:43:in `<main>'
# # 	6: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/modify_vm_interface.rb:16:in `destroy_vm_interface'
# # 	5: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/create_vm.rb:194:in `create_interface'
# # 	4: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/create_vm.rb:165:in `create_nic_backing'
# # 	3: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/get_network.rb:15:in `get_raw_network'
# # 	2: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/get_network.rb:23:in `get_all_raw_networks'
# # 	1: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/compute.rb:691:in `list_container_view'
# # /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/compute.rb:691:in `public_send': undefined method `networkFolder' for nil:NilClass (NoMethodError)
# interface = vm.interfaces.first
# conn.destroy_vm_interface(vm_id, interface: interface)


# # @note Failed at destroy_vm_interface() when bypassede datacenter
# # # @note Failed at destroy_vm_interface() even provided datacenter path/name
# # Traceback (most recent call last):
# # 	7: from test.rb:58:in `<main>'
# # 	6: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/modify_vm_interface.rb:16:in `destroy_vm_interface'
# # 	5: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/create_vm.rb:194:in `create_interface'
# # 	4: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/create_vm.rb:165:in `create_nic_backing'
# # 	3: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/get_network.rb:15:in `get_raw_network'
# # 	2: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/get_network.rb:23:in `get_all_raw_networks'
# # 	1: from /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/compute.rb:691:in `list_container_view'
# # /home/kensoncheung/.gem/ruby/2.5.3/gems/fog-vsphere-2.4.0/lib/fog/vsphere/compute.rb:691:in `public_send': undefined method `networkFolder' for nil:NilClass (NoMethodError)
# datacenter = conn.list_datacenters.first[:path]
# interface = vm.interfaces.first
# conn.destroy_vm_interface(vm_id, key: interface.key, mac: interface.mac, type: interface.type, datacenter: datacenter)


```

**Comment by timogoebel** [comment]
@scambra: Does that sound familiar to you?

**Comment by scambra** [comment]
I added datacenter option to destroy_vm_interface call to fix calling get_interface_from_options, but it's needed for create_interface calling now. I have added another commit to PR.
